# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb122799510df9c65fef51b84a59f8b987869375f53484ac8ae04906f1ba7417e737bbe32e12aca350a477171ac6101d3c336c6a07224bf3c8c48add224b04e

test:
  secret_key_base: b90d28b357de3d92d731c4e9fc256c5a5c5e414a7b03626447a242f73a4e05c189a9d95e6ce75030013e222efbff8caaecb8eeb44296ba1e4cc04326669aea23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
